#!/bin/bash
# lammps_batch_run.sh
# This script automates multiple runs of LAMMPS simulations with varying protein counts
# and saves only the trajectory files to a single directory.

# Ensure we have the required arguments
if (( $# != 6 )); then
    echo "Usage: lammps_batch_run.sh nsites sep n_min n_max n_runs traj_dir"
    exit 1
fi

nsites=$1     # Number of transcription units (TUs)
sep=$2        # Linear separation between TUs (in beads)
n_min=$3      # Minimum number of proteins (e.g., 10)
n_max=$4      # Maximum number of proteins (e.g., 100)
n_runs=$5     # Number of repetitions per protein count
traj_dir=$6   # Directory to store trajectory files

# Ensure trajectory directory exists
mkdir -p "$traj_dir"

# Loop over protein counts
for nprots in $(seq $n_min 10 $n_max); do
    echo "Generating input file for nprots=$nprots"
    ./lammps_init.sh $nsites $sep $nprots "$traj_dir"
    
    for run in $(seq 1 $n_runs); do
        echo "Running simulation for nprots=$nprots, run=$run"
        
        # Run the simulation
        run_script="run_noise_Ns_${nsites}_l_${sep}_Np_${nprots}_run_${run}.sh"
        if [[ -f $run_script ]]; then
            lmp_exe=$(which lmp)  # Ensure LAMMPS executable is found
            if [[ -z "$lmp_exe" ]]; then
                echo "Error: LAMMPS executable (lmp) not found!"
                exit 1
            fi
            $lmp_exe < "in.lammps" > /dev/null 2>&1
            
            # Move trajectory files to the designated directory
            mv *.lammpstrj "$traj_dir/"
        else
            echo "Error: Run script $run_script not found!"
        fi
    done
    
    # Cleanup: Remove the input file and any other temporary files generated by lammps_init.sh
    echo "Cleaning up temporary files for nprots=$nprots"
    rm -f in.lammps
    rm -f run_noise_Ns_${nsites}_l_${sep}_Np_${nprots}_run_*.sh

done

echo "All simulations completed. Trajectory files saved in $traj_dir."
